CREATE TABLE accounts (
                               id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                               username VARCHAR(100) NOT NULL UNIQUE,
                               password VARCHAR(255) NOT NULL,
                               created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
                               updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX idx_accounts_username ON accounts (username);